In [1]:
import torch 
import torch.nn as nn
import pickle
from torch.utils.data import DataLoader, Dataset
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
import os
import torch.nn.functional as F

os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['CUDA_VISIBLE_DEVICES'] = '2'
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


/home/jhmoon/venvFL/env/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
with open('../multiFL/sensIT/weights/combined_weights.pickle', 'rb') as f:
    data1 = pickle.load(f)

In [4]:
parameters = []
modals = ['acoustic', 'seismic', 'combined']
for i in modals:
    with open('/home/jhmoon/venvFL/2023-paper-Federated_Learning/multiFL/sensIT/weights/'+i+'_weights.pickle', 'rb') as f:
        data = pickle.load(f)
        parameters.append(data)

In [42]:
0.16793582 + 1.73850626e-01

0.341786446

In [53]:
parameters[0][5]

array([-0.08748538,  0.11064506,  0.2118959 ,  0.00230611, -0.14275293,
        0.08237765,  0.14774989,  0.10490526, -0.18172738,  0.24118485,
       -0.08349203,  0.01528702, -0.11052497, -0.055976  ,  0.01051702,
        0.08748504], dtype=float32)

In [50]:
parameters[1][5]

array([-0.06365526,  0.12841164,  0.14366466, -0.02249604, -0.12527254,
        0.01222751,  0.15078573,  0.13521458, -0.1635928 ,  0.1657714 ,
       -0.12832288,  0.02810126, -0.09335352, -0.114896  ,  0.00706776,
        0.03649428], dtype=float32)

In [51]:
parameters[2][5]

array([ 0.20220259,  0.13033639,  0.12800704, -0.06475664, -0.04006581,
        0.12088747,  0.04621652,  0.18229635,  0.20121178,  0.16857632,
        0.08287422, -0.11505114,  0.05854994,  0.04866898, -0.03849654,
        0.014607  ], dtype=float32)

In [52]:
(parameters[0][5] + parameters[1][5] + parameters[2][5]) / 3

array([ 0.01702065,  0.12313103,  0.1611892 , -0.02831552, -0.1026971 ,
        0.07183088,  0.11491738,  0.14080541, -0.04803613,  0.19184418,
       -0.04298024, -0.02388762, -0.04844285, -0.04073434, -0.00697059,
        0.04619544], dtype=float32)

In [7]:
data1

[array([[ 0.01473692, -0.08233635, -0.04315492, ...,  0.02950101,
         -0.04219197, -0.01716765],
        [ 0.15205336,  0.0521142 ,  0.09288424, ...,  0.05788887,
          0.10540593, -0.07192094],
        [ 0.04559253, -0.06202829,  0.09280962, ...,  0.00753483,
         -0.04888826, -0.04434061],
        ...,
        [-0.00599087, -0.12753661, -0.05109057, ...,  0.09543911,
          0.05214577, -0.05690293],
        [ 0.08031798,  0.06951158,  0.09535187, ..., -0.11202417,
         -0.0997164 ,  0.07131494],
        [-0.10287038, -0.15981415, -0.07832343, ...,  0.09636814,
          0.07599012,  0.03378509]], dtype=float32),
 array([-0.02462531,  0.10708216,  0.02358895,  0.01630341, -0.00149157,
         0.01118014,  0.09509651,  0.14081329, -0.06775125,  0.1346242 ,
        -0.0275601 ,  0.08418267,  0.00502005, -0.05104493,  0.00807615,
         0.04730692, -0.02745045,  0.04011538,  0.13539073,  0.03590843,
         0.01804212,  0.15102242, -0.02633748,  0.01626055,  0.149

In [9]:
with open('../Data/acoustic.pickle', 'rb') as f:
    data1 = pickle.load(f)
with open('../Data/seismic.pickle', 'rb') as f:
    data2 = pickle.load(f)
    

In [114]:
with open('../Data/combined.pickle', 'rb') as f:
    data = pickle.load(f)

In [115]:
data

class         0         1         2         3         4         5  \
0          3 -0.023321 -0.023527 -0.022061 -0.022273 -0.017079  0.018815   
1          1 -0.136421 -0.092407 -0.131769  0.574799 -0.073130  0.021133   
2          3  0.134293  0.138123  0.525289  1.000000  0.832403  0.659512   
3          3  0.712613  0.782345  0.190930  0.229841  0.560167  0.192150   
4          2  0.197980  0.300174  0.130691  0.802940  1.000000  0.099832   
...      ...       ...       ...       ...       ...       ...       ...   
78818      3 -0.012863  0.012005 -0.018340 -0.009440 -0.033045  0.098008   
78819      2 -0.024249 -0.024640 -0.021435 -0.038170 -0.020313 -0.011039   
78820      3 -0.059299  0.027528 -0.092111  0.653803  0.296419  1.000000   
78821      3 -0.017755  0.003629 -0.001410  0.027432  0.071065  1.000000   
78822      3 -0.018382  0.088634  0.170688  0.165125  1.000000  0.045117   

              6         7         8  ...        90        91        92  \
0      1.000000  0.031178 -0.017721  ... -0.038098 -0.035813 -0.036718   
1      0.099456  1.000000  0.614752  ... -0.042590 -0.045936 -0.045755   
2     -0.047688  0.097587  0.014862  ... -0.019597 -0.046355 -0.016725   
3      1.000000  0.783759 -0.025315  ...  0.063093 -0.020576 -0.054475   
4     -0.009243  0.350689  0.281720  ... -0.063700 -0.047797 -0.032164   
...         ...       ...       ...  ...       ...       ...       ...   
78818  1.000000  0.135341  0.145462  ... -0.069438 -0.023398 -0.072769   
78819  1.000000  0.070916  0.121450  ... -0.035993 -0.035162 -0.035777   
78820 -0.040911  0.927669 -0.082818  ... -0.184531 -0.013405  0.358282   
78821  0.003929 -0.015067 -0.013738  ... -0.027309  0.003666 -0.051606   
78822  0.030288  0.053111  0.020284  ... -0.068714  0.112066  0.031503   

             93        94        95        96        97        98        99  
0     -0.038129 -0.033562 -0.038832 -0.038019 -0.037385 -0.034283 -0.039099  
1     -0.045720 -0.045836 -0.045605 -0.044757 -0.046381 -0.043888 -0.045910  
2     -0.110025 -0.074977 -0.020507 -0.081088 -0.117135  0.124611 -0.084323  
3      0.056441 -0.033763 -0.020097 -0.038449 -0.030611  0.015814 -0.029294  
4     -0.056727 -0.064532 -0.039657 -0.054612 -0.004255 -0.046586 -0.053346  
...         ...       ...       ...       ...       ...       ...       ...  
78818 -0.036016 -0.059330 -0.054264  0.068717 -0.082765 -0.063361 -0.058121  
78819 -0.035664 -0.036003 -0.035998 -0.035592 -0.035893 -0.035913 -0.035753  
78820  0.185890  0.470470  0.242505  0.240674 -0.109372  0.071049  0.615857  
78821 -0.022456  0.132588 -0.101000 -0.098870  0.060842 -0.020554 -0.055325  
78822 -0.077510 -0.098591 -0.038509  0.203295  0.028393  0.095316 -0.097685  

[78823 rows x 101 columns]

In [10]:
data1

class         0         1         2         3         4         5  \
0          2 -0.030057 -0.027216 -0.016126  0.006233  0.053416  1.000000   
1          3  0.124642  1.000000  0.608303  0.008150  0.717687 -0.036154   
2          3 -0.086143 -0.130700 -0.161727 -0.164976  0.577297  0.088806   
3          3 -0.017615  0.021958 -0.002278  0.045736  1.000000  0.026328   
4          2 -0.013705 -0.021804 -0.019416 -0.017692  1.000000 -0.022303   
...      ...       ...       ...       ...       ...       ...       ...   
78818      3 -0.196578 -0.190513 -0.189601 -0.190071 -0.134310  0.183397   
78819      3 -0.061304 -0.057746 -0.045711 -0.055745  0.027025  1.000000   
78820      3  0.919410  1.000000  0.368404  0.540824  0.348019  0.020499   
78821      3  1.000000  0.135210  0.001155  0.033463  0.043519 -0.021910   
78822      3  1.000000  0.408754  0.469056  0.152544  0.104508  0.074612   

              6         7         8  ...        40        41        42  \
0      0.031091  0.015465 -0.013044  ... -0.029370 -0.030332 -0.023607   
1     -0.047996 -0.023177 -0.026854  ... -0.057607 -0.057537 -0.058274   
2     -0.094891  1.000000  0.151082  ... -0.172071 -0.170827 -0.171194   
3     -0.006924 -0.015067  0.009032  ... -0.031494 -0.031255 -0.031199   
4     -0.021477 -0.016256 -0.003198  ... -0.015685 -0.024433 -0.024608   
...         ...       ...       ...  ...       ...       ...       ...   
78818  1.000000  0.165482  0.058812  ... -0.192840 -0.195942 -0.191606   
78819  0.027467 -0.001114 -0.034559  ... -0.057418 -0.058316 -0.053983   
78820 -0.046345 -0.049503 -0.072119  ... -0.075835 -0.075814 -0.075791   
78821  0.156502 -0.017126 -0.022533  ... -0.032626 -0.032628 -0.032633   
78822  0.182801  0.184384  0.298208  ... -0.099466 -0.099291 -0.097173   

             43        44        45        46        47        48        49  
0     -0.031657 -0.028310 -0.031300 -0.031211 -0.030391 -0.030794 -0.031352  
1     -0.058113 -0.058398 -0.058491 -0.058231 -0.058531 -0.057697 -0.058402  
2     -0.168016 -0.170520 -0.171233 -0.169749 -0.171479 -0.171045 -0.170937  
3     -0.030970 -0.031537 -0.031499 -0.030825 -0.031589 -0.031559 -0.031543  
4     -0.025368 -0.025230 -0.025162 -0.025535 -0.024619 -0.024239 -0.024822  
...         ...       ...       ...       ...       ...       ...       ...  
78818 -0.193735 -0.195426 -0.195237 -0.193389 -0.194077 -0.193594 -0.195067  
78819 -0.059059 -0.059256 -0.057427 -0.058625 -0.056731 -0.053740 -0.050476  
78820 -0.075812 -0.075693 -0.075819 -0.075829 -0.075817 -0.075885 -0.075873  
78821 -0.032621 -0.032624 -0.032624 -0.032615 -0.032636 -0.032619 -0.032639  
78822 -0.096741 -0.098397 -0.098376 -0.099204 -0.097753 -0.098066 -0.097607  

[78823 rows x 51 columns]

In [117]:
data2

class         0         1         2         3         4         5  \
0          3 -0.311070  0.602284 -0.295414 -0.135353 -0.272519  0.470501   
1          1 -0.036019  1.000000  0.044621 -0.017574  0.095875 -0.015582   
2          1 -0.102323  0.267455  0.789374  1.000000 -0.097091 -0.016171   
3          3 -0.560520 -0.450013  0.732302  0.579498  0.405977 -0.554563   
4          1 -0.062265 -0.059779  0.269739  0.126958  0.393020  1.000000   
...      ...       ...       ...       ...       ...       ...       ...   
78818      3 -0.269766  0.196617  0.072544 -0.194465 -0.109302  0.390684   
78819      3 -0.027526  1.000000 -0.006795 -0.026603 -0.024834 -0.026691   
78820      3 -0.119000  1.000000 -0.021042  0.098366 -0.013572 -0.012918   
78821      1 -0.065489 -0.026753  0.904410  0.025899  0.353314  1.000000   
78822      3 -0.151503  1.000000 -0.087561  0.028637  0.187530  0.135972   

              6         7         8  ...        40        41        42  \
0      0.055555  0.350612  0.283464  ... -0.121085  0.458755 -0.287152   
1     -0.010842 -0.030141 -0.020132  ... -0.029158 -0.034659 -0.034904   
2      0.186275  0.598286 -0.049404  ... -0.096673 -0.099150 -0.100942   
3      0.420540  0.075622 -0.501731  ...  0.160053  0.183239  0.330863   
4      0.914650 -0.019336 -0.032771  ... -0.061744 -0.062252 -0.062077   
...         ...       ...       ...  ...       ...       ...       ...   
78818 -0.089140 -0.155741  1.000000  ...  0.053338  0.100374  0.595054   
78819 -0.027017 -0.009539 -0.011659  ... -0.027411 -0.025038 -0.027022   
78820  0.008290  0.012824  0.045739  ... -0.008321  0.119679 -0.042712   
78821  0.005112 -0.002746 -0.028185  ... -0.061065 -0.064014 -0.063624   
78822 -0.146437  0.414554 -0.060040  ...  0.155516 -0.143649  0.203902   

             43        44        45        46        47        48        49  
0      0.004847 -0.280585 -0.125173  0.010386 -0.288257  0.115472  0.013447  
1     -0.035061  0.006946 -0.035320 -0.032870 -0.015724 -0.032703 -0.035713  
2     -0.101388 -0.100168 -0.101975 -0.100745 -0.101671 -0.101034 -0.101691  
3     -0.430148 -0.050102 -0.469018 -0.378305 -0.347293 -0.307555  0.100423  
4     -0.062227 -0.062246 -0.062236 -0.062251 -0.062113 -0.062113 -0.062244  
...         ...       ...       ...       ...       ...       ...       ...  
78818  0.099036  0.045020  0.042506 -0.061369 -0.189697  0.172433 -0.179482  
78819 -0.024138 -0.027477 -0.025119 -0.027264 -0.026643 -0.022561 -0.025719  
78820 -0.104822  0.204603  0.005783 -0.094751 -0.004194 -0.043655 -0.109560  
78821 -0.065410 -0.065471 -0.064557 -0.064141 -0.065216 -0.062876 -0.065382  
78822 -0.002047  0.087228 -0.100472 -0.122130 -0.073658 -0.097420 -0.045243  

[78823 rows x 51 columns]

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [86]:
data1['class'] = data1['class'].apply(lambda x: 0 if x == 1 else (1 if x == 2 else 2)) 

In [87]:
data1

class         0         1         2         3         4         5  \
0          1 -0.030057 -0.027216 -0.016126  0.006233  0.053416  1.000000   
1          2  0.124642  1.000000  0.608303  0.008150  0.717687 -0.036154   
2          2 -0.086143 -0.130700 -0.161727 -0.164976  0.577297  0.088806   
3          2 -0.017615  0.021958 -0.002278  0.045736  1.000000  0.026328   
4          1 -0.013705 -0.021804 -0.019416 -0.017692  1.000000 -0.022303   
...      ...       ...       ...       ...       ...       ...       ...   
78818      2 -0.196578 -0.190513 -0.189601 -0.190071 -0.134310  0.183397   
78819      2 -0.061304 -0.057746 -0.045711 -0.055745  0.027025  1.000000   
78820      2  0.919410  1.000000  0.368404  0.540824  0.348019  0.020499   
78821      2  1.000000  0.135210  0.001155  0.033463  0.043519 -0.021910   
78822      2  1.000000  0.408754  0.469056  0.152544  0.104508  0.074612   

              6         7         8  ...        40        41        42  \
0      0.031091  0.015465 -0.013044  ... -0.029370 -0.030332 -0.023607   
1     -0.047996 -0.023177 -0.026854  ... -0.057607 -0.057537 -0.058274   
2     -0.094891  1.000000  0.151082  ... -0.172071 -0.170827 -0.171194   
3     -0.006924 -0.015067  0.009032  ... -0.031494 -0.031255 -0.031199   
4     -0.021477 -0.016256 -0.003198  ... -0.015685 -0.024433 -0.024608   
...         ...       ...       ...  ...       ...       ...       ...   
78818  1.000000  0.165482  0.058812  ... -0.192840 -0.195942 -0.191606   
78819  0.027467 -0.001114 -0.034559  ... -0.057418 -0.058316 -0.053983   
78820 -0.046345 -0.049503 -0.072119  ... -0.075835 -0.075814 -0.075791   
78821  0.156502 -0.017126 -0.022533  ... -0.032626 -0.032628 -0.032633   
78822  0.182801  0.184384  0.298208  ... -0.099466 -0.099291 -0.097173   

             43        44        45        46        47        48        49  
0     -0.031657 -0.028310 -0.031300 -0.031211 -0.030391 -0.030794 -0.031352  
1     -0.058113 -0.058398 -0.058491 -0.058231 -0.058531 -0.057697 -0.058402  
2     -0.168016 -0.170520 -0.171233 -0.169749 -0.171479 -0.171045 -0.170937  
3     -0.030970 -0.031537 -0.031499 -0.030825 -0.031589 -0.031559 -0.031543  
4     -0.025368 -0.025230 -0.025162 -0.025535 -0.024619 -0.024239 -0.024822  
...         ...       ...       ...       ...       ...       ...       ...  
78818 -0.193735 -0.195426 -0.195237 -0.193389 -0.194077 -0.193594 -0.195067  
78819 -0.059059 -0.059256 -0.057427 -0.058625 -0.056731 -0.053740 -0.050476  
78820 -0.075812 -0.075693 -0.075819 -0.075829 -0.075817 -0.075885 -0.075873  
78821 -0.032621 -0.032624 -0.032624 -0.032615 -0.032636 -0.032619 -0.032639  
78822 -0.096741 -0.098397 -0.098376 -0.099204 -0.097753 -0.098066 -0.097607  

[78823 rows x 51 columns]

In [81]:
device = 'cpu'

In [88]:
X = data1[[str(x) for x in range(50)]]
y = data1['class']
X = X.values
y = y.values
# y = torch.tensor(y.values)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=34)


In [77]:
ms = MinMaxScaler()
ss = StandardScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.fit_transform(X_test)
# y_train = y_train.reshape(-1, 1)
# y_test = y_test.reshape(-1, 1)

In [89]:
X_train

array([[ 0.97204102,  0.05565637, -0.03050711, ..., -0.10396622,
        -0.10708707, -0.11608528],
       [-0.06783397, -0.06778439, -0.06220271, ..., -0.06615854,
        -0.06337908, -0.00742759],
       [-0.02546111, -0.02505541, -0.0245985 , ..., -0.02555124,
        -0.024686  , -0.02069945],
       ...,
       [-0.06632779,  0.05824382,  0.08819027, ..., -0.07748754,
        -0.07818329, -0.07673419],
       [-0.03275923, -0.02356955, -0.0218401 , ..., -0.03407454,
        -0.02735483, -0.03268085],
       [-0.02716259,  0.0521438 ,  0.0069933 , ..., -0.03735497,
        -0.03803071, -0.0374999 ]])

In [90]:
class customDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.len = len(self.X)
    def __getitem__(self, index):
        return self.X[index], self.y[index]
    def __len__(self):
        return self.len

In [91]:
train_data = customDataset(torch.FloatTensor(X_train), torch.LongTensor(y_train))
test_data = customDataset(torch.FloatTensor(X_test), torch.LongTensor(y_test))

train_loader = DataLoader(train_data, batch_size = 64, shuffle= True)
test_loader = DataLoader(test_data, batch_size = 64, shuffle= True)

In [92]:
class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel,self).__init__()
        self.fc1 = nn.Linear(50, 32)
        self.fc2 = nn.Linear(32,32)
        self.fc3 = nn.Linear(32,3)
        self.droput = nn.Dropout(0.2)

    def forward(self,x):

        x = x.view(-1,50)
        x = F.relu(self.fc1(x))
        x = self.droput(x)
        x = F.relu(self.fc2(x))
        x = self.droput(x)
        x = self.fc3(x)

        return x

model = CustomModel().to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

for epoch in tqdm(range(1000)):
    cost = 0.0

    for x, y in train_loader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_loader)

    if (epoch + 1) % 100 == 0:
        print(f"Epoch : {epoch+1:4d}, Cost : {cost:.3f}")


# with torch.no_grad():
#     model.eval()
#     classes = {0: "acute triangle", 1: "right triangle", 2: "obtuse triangle"}
#     inputs = torch.FloatTensor([
#         [9.02, 9.77, 9.96], # 0 | acute triangle
#         [8.01, 8.08, 8.32], # 0 | acute triangle
#         [3.55, 5.15, 6.26], # 1 | right triangle
#         [3.32, 3.93, 5.14], # 1 | right triangle
#         [4.39, 5.56, 9.99], # 2 | obtuse triangle
#         [3.01, 3.08, 9.98], # 2 | obtuse triangle
#         [5.21, 5.38, 5.39], # 0 | acute triangle
#         [3.85, 6.23, 7.32], # 1 | right triangle
#         [4.16, 4.98, 8.54], # 2 | obtuse triangle
#     ]).to(device)
#     outputs = model(inputs)
    
#     print('---------')
#     print(outputs)
#     print(torch.round(F.softmax(outputs, dim=1), decimals=2))
#     print(outputs.argmax(1))
#     print(list(map(classes.get, outputs.argmax(1).tolist())))

  3%|▎         | 30/1000 [00:33<18:07,  1.12s/it]


KeyboardInterrupt: 

In [213]:
nodes = 8
input_dim = X_train.shape[1]
hidden_dim = int(input_dim/nodes)
output_dim = 3

In [215]:
class MultiClassClassifierModule(nn.Module):
    def __init__(
            self,
            input_dim=input_dim,
            hidden_dim=hidden_dim,
            output_dim=output_dim,
            dropout=0.5,
    ):
        super(MultiClassClassifierModule, self).__init__()
        self.dropout = nn.Dropout(dropout)

        self.hidden = nn.Linear(input_dim, hidden_dim)
        self.output = nn.Linear(hidden_dim, output_dim)

    def forward(self, X, **kwargs):
        X = F.relu(self.hidden(X))
        X = self.dropout(X)
        X = F.softmax(self.output(X), dim=-1)
        return X

In [222]:
class Multiclass(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(4, 8)
        self.act = nn.ReLU()
        self.output = nn.Linear(8, 3)
        
    def forward(self, x):
        x = self.act(self.hidden(x))
        x = self.output(x)
        return x

52811

In [223]:
class neuNet(nn.Module):
    def __init__(self):
        super(neuNet,self).__init__()
        self.fc1 = nn.Linear(50, 32)
        self.fc2 = nn.Linear(32,32)
        self.fc3 = nn.Linear(32,3)
        self.droput = nn.Dropout(0.2)

    def forward(self,x):

        x = x.view(-1,50)
        x = F.relu(self.fc1(x))
        x = self.droput(x)
        x = F.relu(self.fc2(x))
        x = self.droput(x)
        x = self.fc3(x)

        return x

In [224]:
model = neuNet().to(device)

In [225]:
model

neuNet(
  (fc1): Linear(in_features=50, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=3, bias=True)
  (droput): Dropout(p=0.2, inplace=False)
)

In [226]:
learning_rate = 0.01
MLP_criterion = nn.CrossEntropyLoss()
Model_optimizer = torch.optim.SGD(model.parameters(),lr =learning_rate)

In [227]:
def accuracy(y_pred, y_test):
    y_pred_tag = torch.round(torch.sigmoid(y_pred))
    # print(y_pred_tag)
    correct_results_sum = (y_pred_tag == y_test).sum().float()
    # print(correct_results_sum)
    acc = correct_results_sum / y_test.shape[0]
    acc = torch.round(acc * 100)
    return acc

In [228]:
epochs = 50
print_epoch = 5
for epoch in range(epochs):
    iteration_loss = 0.
    iteration_accuracy = 0.
    
    model.train()
    for i, data in enumerate(train_loader):
        X, y = data
        X, y = X.to(device), y.to(device)
        y_pred = model(X.float())
        loss = MLP_criterion(y_pred, y.reshape(-1, 1).float())
        
        iteration_loss += loss
        iteration_accuracy += accuracy(y_pred, y)
        Model_optimizer.zero_grad()
        loss.backward()
        Model_optimizer.step()
    
    if epoch % print_epoch == 0:
        print(f'Train: epoch: {epoch} - loss: {(iteration_loss/(i+1)):.5f}; acc: {(iteration_accuracy/(i+1)):.3f}')
    
    iteration_loss = 0.
    iteration_accuracy = 0.
    model.eval()
    for i, data in enumerate(test_loader):
        X, y = data
        X, y = X.to(device), y.to(device)
        y_pred = model(X.float())
        loss = MLP_criterion(y_pred, y.reshape(-1, 1).float())
        
        iteration_loss += loss
        iteration_accuracy += accuracy(y_pred, y)
        Model_optimizer.zero_grad()
        loss.backward()
        Model_optimizer.step()
    
    if epoch % print_epoch == 0:
        print(f'Test: epoch: {epoch} - loss: {(iteration_loss/(i+1)):.5f}; acc: {(iteration_accuracy/(i+1)):.3f}')
    



RuntimeError: 0D or 1D target tensor expected, multi-target not supported

In [236]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader


class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.a = df.iloc[:, 0].values
        self.b = df.iloc[:, 1].values
        self.c = df.iloc[:, 2].values
        self.y = df.iloc[:, 3].values
        self.y = list(map(self.string_to_vector, self.y))
        self.length = len(df)

    def string_to_vector(self, value):
        data = {"acute triangle": 0, "right triangle": 1, "obtuse triangle": 2}
        return data.get(value, None)

    def __getitem__(self, index):
        x = torch.FloatTensor(sorted([self.a[index], self.b[index], self.c[index]]))
        y = torch.LongTensor(self.y)[index]
        return x, y

    def __len__(self):
        return self.length


class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()

        self.layer = nn.Sequential(
            nn.Linear(3, 3)
        )

    def forward(self, x):
        x = self.layer(x)
        return x


train_dataset = CustomDataset("../Data/dataset.csv")
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.001)

for epoch in range(1000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 100 == 0:
        print(f"Epoch : {epoch+1:4d}, Cost : {cost:.3f}")


with torch.no_grad():
    model.eval()
    classes = {0: "acute triangle", 1: "right triangle", 2: "obtuse triangle"}
    inputs = torch.FloatTensor([
        [9.02, 9.77, 9.96], # 0 | acute triangle
        [8.01, 8.08, 8.32], # 0 | acute triangle
        [3.55, 5.15, 6.26], # 1 | right triangle
        [3.32, 3.93, 5.14], # 1 | right triangle
        [4.39, 5.56, 9.99], # 2 | obtuse triangle
        [3.01, 3.08, 9.98], # 2 | obtuse triangle
        [5.21, 5.38, 5.39], # 0 | acute triangle
        [3.85, 6.23, 7.32], # 1 | right triangle
        [4.16, 4.98, 8.54], # 2 | obtuse triangle
    ]).to(device)
    outputs = model(inputs)
    
    print('---------')
    print(outputs)
    print(torch.round(F.softmax(outputs, dim=1), decimals=2))
    print(outputs.argmax(1))
    print(list(map(classes.get, outputs.argmax(1).tolist())))

Epoch : 1000, Cost : 0.205
Epoch : 2000, Cost : 0.131
Epoch : 3000, Cost : 0.096


KeyboardInterrupt: 

In [1]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader


class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.a = df.iloc[:, 0].values
        self.b = df.iloc[:, 1].values
        self.c = df.iloc[:, 2].values
        self.y = df.iloc[:, 3].values
        self.y = list(map(self.string_to_vector, self.y))
        self.length = len(df)

    def string_to_vector(self, value):
        data = {"acute triangle": 0, "right triangle": 1, "obtuse triangle": 2}
        return data.get(value, None)

    def __getitem__(self, index):
        x = torch.FloatTensor(sorted([self.a[index], self.b[index], self.c[index]]))
        y = torch.LongTensor(self.y)[index]
        return x, y

    def __len__(self):
        return self.length

/home/jhmoon/venvFL/env/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
train_dataset = CustomDataset("../Data/dataset.csv")

In [4]:
df = pd.read_csv('../Data/dataset.csv')

In [6]:
df.iloc[:, 0].values

array([3.16, 9.46, 7.23, ..., 9.24, 7.86, 6.11])