In [2]:
import torch 
import torch.nn as nn
import pickle
from torch.utils.data import DataLoader, Dataset, random_split
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
import os
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['CUDA_VISIBLE_DEVICES'] = '2'
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


/home/jhmoon/venvFL/env/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
with open('../Data/acoustic.pickle', 'rb') as f:
    data1 = pickle.load(f)
with open('../Data/seismic.pickle', 'rb') as f:
    data2 = pickle.load(f)
with open('../Data/combined.pickle', 'rb') as f:
    data = pickle.load(f)

# data1['class'] = data1['class'].apply(lambda x: 0 if x == 1 else (1 if x == 2 else 2)) 

In [13]:
data.iloc[:5000]['class'].value_counts()

3    2563
2    1352
1    1085
Name: class, dtype: int64

In [4]:
X = data1[[str(x) for x in range(50)]]
y = data1['class']
X = X.values
y = y.values


# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=34)


In [6]:
y

array([2, 3, 3, ..., 3, 3, 3])

In [8]:
class customDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.len = len(self.X)
    def __getitem__(self, index):
        return self.X[index], self.y[index]
    def __len__(self):
        return self.len

In [9]:
train_data = customDataset(torch.FloatTensor(X_train), torch.LongTensor(y_train))
test_data = customDataset(torch.FloatTensor(X_test), torch.LongTensor(y_test))

train_loader = DataLoader(train_data, batch_size = 64, shuffle= True)
test_loader = DataLoader(test_data, batch_size = 64, shuffle= True)

In [16]:
class customDataset(Dataset):
        def __init__(self, X, y):
            self.X = X
            self.y = y
            self.len = len(self.X)
        def __getitem__(self, index):
            return self.X[index], self.y[index]
        def __len__(self):
            return self.len

In [40]:
trainset

(array([[-0.03005682, -0.02721567, -0.01612586, ..., -0.03039098,
         -0.0307941 , -0.03135211],
        [ 0.12464222,  1.        ,  0.6083032 , ..., -0.05853093,
         -0.05769675, -0.05840248],
        [-0.0861426 , -0.13070015, -0.16172661, ..., -0.17147881,
         -0.17104471, -0.17093658],
        ...,
        [ 0.9194103 ,  1.        ,  0.36840399, ..., -0.07581654,
         -0.07588511, -0.0758732 ],
        [ 1.        ,  0.13520986,  0.00115452, ..., -0.03263643,
         -0.03261888, -0.03263868],
        [ 1.        ,  0.40875378,  0.46905633, ..., -0.09775266,
         -0.09806576, -0.09760697]]),
 array([2, 3, 3, ..., 3, 3, 3]))

In [42]:
with open('/home/jhmoon/venvFL/2023-paper-Federated_Learning/Data/trainset5000.pickle', 'rb') as trs:
    trainset = pickle.load(trs)

In [58]:
X = torch.tensor(X)

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=34)


In [76]:
torchvisionType_for_trainVal = []
for i in range(len(X_train)):
    torchvisionType_for_trainVal.append((X_train[i], y_train[i]))

In [79]:
testloader = DataLoader(torchvisionType_for_trainVal, batch_size=32)

In [80]:
testloader

In [62]:
trainset[1]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [65]:
X

tensor([[-0.0301, -0.0272, -0.0161,  ..., -0.0304, -0.0308, -0.0314],
        [ 0.1246,  1.0000,  0.6083,  ..., -0.0585, -0.0577, -0.0584],
        [-0.0861, -0.1307, -0.1617,  ..., -0.1715, -0.1710, -0.1709],
        ...,
        [ 0.9194,  1.0000,  0.3684,  ..., -0.0758, -0.0759, -0.0759],
        [ 1.0000,  0.1352,  0.0012,  ..., -0.0326, -0.0326, -0.0326],
        [ 1.0000,  0.4088,  0.4691,  ..., -0.0978, -0.0981, -0.0976]],
       dtype=torch.float64)

In [66]:
values = []
for i in range(len(X)):
    values.append((X[i], y[i]))

In [70]:
values

[(tensor([-0.0301, -0.0272, -0.0161,  0.0062,  0.0534,  1.0000,  0.0311,  0.0155,
          -0.0130,  0.0013,  0.0458, -0.0291,  0.0212, -0.0197, -0.0163, -0.0272,
          -0.0287, -0.0294, -0.0220, -0.0309, -0.0315, -0.0313, -0.0224, -0.0180,
          -0.0297, -0.0273, -0.0282, -0.0304, -0.0319, -0.0307, -0.0309, -0.0288,
          -0.0293, -0.0306, -0.0307, -0.0311, -0.0308, -0.0309, -0.0305, -0.0314,
          -0.0294, -0.0303, -0.0236, -0.0317, -0.0283, -0.0313, -0.0312, -0.0304,
          -0.0308, -0.0314], dtype=torch.float64),
  2),
 (tensor([ 0.1246,  1.0000,  0.6083,  0.0082,  0.7177, -0.0362, -0.0480, -0.0232,
          -0.0269, -0.0506, -0.0518, -0.0540, -0.0575, -0.0542, -0.0583, -0.0568,
          -0.0559, -0.0533, -0.0504, -0.0584, -0.0576, -0.0566, -0.0543, -0.0570,
          -0.0562, -0.0524, -0.0567, -0.0577, -0.0582, -0.0580, -0.0579, -0.0574,
          -0.0579, -0.0585, -0.0551, -0.0581, -0.0575, -0.0585, -0.0585, -0.0579,
          -0.0576, -0.0575, -0.0583, -0.0

In [68]:
values

[(tensor([-0.0301, -0.0272, -0.0161,  0.0062,  0.0534,  1.0000,  0.0311,  0.0155,
          -0.0130,  0.0013,  0.0458, -0.0291,  0.0212, -0.0197, -0.0163, -0.0272,
          -0.0287, -0.0294, -0.0220, -0.0309, -0.0315, -0.0313, -0.0224, -0.0180,
          -0.0297, -0.0273, -0.0282, -0.0304, -0.0319, -0.0307, -0.0309, -0.0288,
          -0.0293, -0.0306, -0.0307, -0.0311, -0.0308, -0.0309, -0.0305, -0.0314,
          -0.0294, -0.0303, -0.0236, -0.0317, -0.0283, -0.0313, -0.0312, -0.0304,
          -0.0308, -0.0314], dtype=torch.float64),
  2),
 (tensor([ 0.1246,  1.0000,  0.6083,  0.0082,  0.7177, -0.0362, -0.0480, -0.0232,
          -0.0269, -0.0506, -0.0518, -0.0540, -0.0575, -0.0542, -0.0583, -0.0568,
          -0.0559, -0.0533, -0.0504, -0.0584, -0.0576, -0.0566, -0.0543, -0.0570,
          -0.0562, -0.0524, -0.0567, -0.0577, -0.0582, -0.0580, -0.0579, -0.0574,
          -0.0579, -0.0585, -0.0551, -0.0581, -0.0575, -0.0585, -0.0585, -0.0579,
          -0.0576, -0.0575, -0.0583, -0.0

In [53]:
temp = random_split(values, [60000, 18823])

In [69]:
trainloaders = []
valloaders = []
for ds in temp:
    print(ds)
    len_val = len(ds) // 10  # 10 % validation set
    len_train = len(ds) - len_val
    lengths = [len_train, len_val]
    ds_train, ds_val = random_split(ds, lengths, torch.Generator().manual_seed(42))
    trainloaders.append(DataLoader(ds_train, batch_size=32, shuffle=True))
    valloaders.append(DataLoader(ds_val, batch_size=32))

In [56]:
valloaders[0]

In [41]:
trainset

(array([[-0.03005682, -0.02721567, -0.01612586, ..., -0.03039098,
         -0.0307941 , -0.03135211],
        [ 0.12464222,  1.        ,  0.6083032 , ..., -0.05853093,
         -0.05769675, -0.05840248],
        [-0.0861426 , -0.13070015, -0.16172661, ..., -0.17147881,
         -0.17104471, -0.17093658],
        ...,
        [ 0.9194103 ,  1.        ,  0.36840399, ..., -0.07581654,
         -0.07588511, -0.0758732 ],
        [ 1.        ,  0.13520986,  0.00115452, ..., -0.03263643,
         -0.03261888, -0.03263868],
        [ 1.        ,  0.40875378,  0.46905633, ..., -0.09775266,
         -0.09806576, -0.09760697]]),
 array([2, 3, 3, ..., 3, 3, 3]))

In [9]:
partition_size = len(trainset) // 2
lengths = [partition_size] * 2
datasets = random_split(trainset, lengths, torch.Generator().manual_seed(42))

In [15]:
trainloaders = []
valloaders = []
for ds in datasets:
    print(ds)
    len_val = len(ds) // 10  # 10 % validation set
    len_train = len(ds) - len_val
    lengths = [len_train, len_val]
    ds_train, ds_val = random_split(ds, lengths, torch.Generator().manual_seed(42))
    trainloaders.append(DataLoader(ds_train, batch_size=32, shuffle=True))
    valloaders.append(DataLoader(ds_val, batch_size=32))

In [25]:
with open('/home/jhmoon/venvFL/2023-paper-Federated_Learning/Data/trainset5000.pickle', 'rb') as trs:
    trainset1 = pickle.load(trs)

In [26]:
partition_size = len(trainset1) // 2
lengths = [partition_size] * 2
datasets1 = random_split(trainset1, lengths, torch.Generator().manual_seed(42))

trainloaders1 = []
valloaders1 = []
for ds in datasets1:
    print(ds)
    len_val = len(ds) // 10  # 10 % validation set
    len_train = len(ds) - len_val
    lengths = [len_train, len_val]
    ds_train, ds_val = random_split(ds, lengths, torch.Generator().manual_seed(42))
    trainloaders1.append(DataLoader(ds_train, batch_size=32, shuffle=True))
    valloaders1.append(DataLoader(ds_val, batch_size=32))

In [88]:
with open('/home/jhmoon/venvFL/2023-paper-Federated_Learning/Data/acoustic.pickle', 'rb') as f:
    data1 = pickle.load(f)

data1['class'] = data1['class'].apply(lambda x: 0 if x == 1 else (1 if x == 2 else 2)) 

X = data1[[str(x) for x in range(50)]]
y = data1['class']
X = X.values
y = y.values
# X = torch.tensor(X)
# y = torch.tensor(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=34)

torchvisionType_for_trainVal = []
for i in range(len(X_train)):
    torchvisionType_for_trainVal.append((X_train[i], y_train[i]))

torchvisionType_for_test = []
for i in range(len(X_test)):
    torchvisionType_for_test.append((X_test[i], y_test[i]))

partition_size = len(torchvisionType_for_trainVal) // 2
lengths = [partition_size] * 2
datasets = random_split(torchvisionType_for_trainVal, lengths, torch.Generator().manual_seed(42))

trainloaders = []
valloaders = []
for ds in datasets:
    len_val = len(ds) // 10  # 10 % validation set
    len_train = len(ds) - len_val
    lengths = [len_train, len_val]
    ds_train, ds_val = random_split(ds, lengths, torch.Generator().manual_seed(42))
    trainloaders.append(DataLoader(ds_train, batch_size = 32, shuffle=True))
    valloaders.append(DataLoader(ds_val, batch_size = 32))
testloader = DataLoader(torchvisionType_for_test, batch_size = 32)


In [103]:
for x, y in trainloaders[0]:
    print(x[0][0].dtype)
    print(y[0].dtype)
    break

torch.float64
torch.int64


In [58]:
for x, y in trainloaders1[0]:
    print(x[0][0][19][0], type(y[1]))
    break

tensor(0.) <class 'torch.Tensor'>


In [102]:
for x, y in trainloaders1[0]:
    print(x[0][0][6][13].dtype)
    print(y[0].dtype)
    break

torch.float32
torch.int64


In [92]:
x = torch.tensor([1,2,3])

In [94]:
y = x * 2.5

In [100]:
y.dtype

torch.float32

In [121]:
with open('../Data/acoustic.pickle', 'rb') as f:
    data1 = pickle.load(f)

data1['class'] = data1['class'].apply(lambda x: 0 if x == 1 else (1 if x == 2 else 2)) 

X = data1[[str(x) for x in range(50)]]
y = data1['class']
X = X.values
y = y.values
# y = torch.tensor(y.values)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=34)

class customDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.len = len(self.X)
    def __getitem__(self, index):
        return self.X[index], self.y[index]
    def __len__(self):
        return self.len

train_data = customDataset(torch.FloatTensor(X_train), torch.LongTensor(y_train))
test_data = customDataset(torch.FloatTensor(X_test), torch.LongTensor(y_test))

train_loader = DataLoader(train_data, batch_size = 128, shuffle= True)
test_loader = DataLoader(test_data, batch_size = 128, shuffle= True)

In [118]:
num_clients = 2
with open('/home/jhmoon/venvFL/2023-paper-Federated_Learning/Data/acoustic.pickle', 'rb') as f:
    data1 = pickle.load(f)

data1['class'] = data1['class'].apply(lambda x: 0 if x == 1 else (1 if x == 2 else 2)) 

X = data1[[str(x) for x in range(50)]]
y = data1['class']
X = X.values
y = y.values
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=34)

torchvisionType_for_trainVal = []
for i in range(len(X_train)):
    torchvisionType_for_trainVal.append((X_train[i], y_train[i]))

torchvisionType_for_test = []
for i in range(len(X_test)):
    torchvisionType_for_test.append((X_test[i], y_test[i]))

partition_size = len(torchvisionType_for_trainVal) // num_clients
lengths = [partition_size] * num_clients
datasets = random_split(torchvisionType_for_trainVal, lengths, torch.Generator().manual_seed(42))

trainloaders = []
valloaders = []
for ds in datasets:
    len_val = len(ds) // 10  # 10 % validation set
    len_train = len(ds) - len_val
    lengths = [len_train, len_val]
    ds_train, ds_val = random_split(ds, lengths, torch.Generator().manual_seed(42))
    trainloaders.append(DataLoader(ds_train, batch_size = 32, shuffle=True))
    valloaders.append(DataLoader(ds_val, batch_size = 32))
testloader = DataLoader(torchvisionType_for_test, batch_size = 32)

In [122]:
for x, y in train_loader:
    print(x.dtype, y.dtype)
    break

torch.float32 torch.int64


In [119]:
for x, y in trainloaders[0]:
    print(x.dtype, y.dtype)
    break

torch.float32 torch.int64
